# Generated by Django 3.2.7 on 2021-09-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('kakao_id', models.BigIntegerField(null=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.deposit')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
