# Generated by Django 3.2.7 on 2021-09-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.PositiveSmallIntegerField()),
                ('income_type', models.CharField(max_length=32)),
                ('income', models.PositiveIntegerField()),
                ('card_usage_amount', models.PositiveIntegerField()),
                ('loan_amount', models.PositiveIntegerField(null=True)),
                ('is_overdue', models.CharField(max_length=32, null=True)),
                ('overdue_tax', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'borrower_informations',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'loan_types',
            },
        ),
        migrations.CreateModel(
            name='RepaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'repayment_types',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('completion_date', models.CharField(max_length=32)),
                ('supply_area', models.FloatField()),
                ('household', models.PositiveSmallIntegerField()),
                ('exclusive_private_area', models.FloatField()),
                ('lease_status', models.CharField(max_length=16)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'securities',
            },
        ),
        migrations.CreateModel(
            name='InvestmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_price', models.PositiveBigIntegerField()),
                ('repayment_day', models.PositiveSmallIntegerField()),
                ('priority_bond_amount', models.PositiveIntegerField()),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.loantype')),
            ],
            options={
                'db_table': 'investment_details',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.PositiveSmallIntegerField()),
                ('return_rate', models.FloatField()),
                ('target_amount', models.IntegerField()),
                ('current_amount', models.IntegerField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.borrowerinformation')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investmentdetail')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.grade')),
                ('repayment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.repaymenttype')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.security')),
            ],
            options={
                'db_table': 'investments',
            },
        ),
    ]
