# Generated by Django 3.2.7 on 2021-09-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('investment', models.IntegerField()),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
