# Generated by Django 3.2.7 on 2021-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_image_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='bidding_rate',
            field=models.FloatField(null=True),
        ),
    ]
