# Generated by Django 3.2.7 on 2021-09-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='transactions.bank'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='withdrawal_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_withdrawal', to='transactions.bank'),
        ),
    ]
