# Generated by Django 3.2.7 on 2021-09-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210915_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_account',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
