# Generated by Django 3.2.7 on 2021-09-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210928_0733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repaymentstate',
            table='repayment_states',
        ),
    ]
