# Generated by Django 3.2.7 on 2021-09-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
        ('investments', '0004_investmentdetail_bidding_rate'),
        ('transactions', '0007_alter_repaymentstate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'investment_states',
            },
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='state',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounts', models.PositiveIntegerField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment')),
                ('investment_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.investmentstate')),
                ('repayment_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.repaymentstate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
    ]
