# Generated by Django 3.2.7 on 2021-09-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
        ('transactions', '0008_auto_20210928_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
