# Generated by Django 3.2.7 on 2021-09-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_repayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amounts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
