# Generated by Django 3.2.7 on 2021-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_portfolio_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amounts',
            field=models.PositiveIntegerField(),
        ),
    ]
